import { ICourse } from "./Course/Course";

export const coursConfig: ICourse[] = [
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
  {
    speakerName: "Avinach Jain",
    title: "Learning Python for Data Analysis and Visualization",
    subTitle: "Vulputate commodo urna quam sagittis mattis aliquam.",
    rateFromFive: 3,
    ratesNumber: "18,465",
    currentPrice: "50,000",
    days: 3,
    hours: 30,
    attendance: "35/50",
    mainPrice: "100,000",
    offerPercentage: 50,
    peopleWishNum: "50",
  },
];
